import { Inter, Poppins } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })
const poppins = Poppins({
    weight: ['400', '500'],
    style:['normal'],
    subsets: ['latin'],
    display: 'swap'
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      <link rel="icon" href="/app/favicon.ico" sizes="any" />
      </head>
      <body className={poppins.className}>{children}</body>
    </html>
  )
}
